export enum PermissionsEnum {
  USERS_READ = "USERS_READ",
  USERS_CREATE = "USERS_CREATE",
  USERS_DELETE = "USERS_DELETE",
  CREDITS_READ = "CREDITS_READ",
  CREDITS_CREATE = "CREDITS_CREATE",
  TRANSACTIONS_READ = "TRANSACTIONS_READ",
  TRANSACTIONS_CREATE = "TRANSACTIONS_CREATE",
}