http:
   port: ${PORT}
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    paths: '/ip'
  authorizer:
    methods: "GET,POST,PUT"
    paths: "/authorizer*"
  credits:
    methods: "GET,POST,PUT"
    paths: "/credits*"
  payments:
    methods: "GET,POST,PUT"
    paths: "/payments*"
  transactions:
    methods: "GET,POST,PUT"
    paths: "/transactions*"
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  authorizerService:
    url: "http://localhost:4000"
  creditsService:
    url: "http://localhost:4001"
  paymentsService:
    url: "http://localhost:4002"
  transactionsService:
    url: "http://localhost:4003"
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
  authorizer:
    apiEndpoints:
      - authorizer
    policies:
      - cors:
          - action:
              origin: "*"
      - proxy:
          - action:
              serviceEndpoint: authorizerService 
              changeOrigin: true
  credits:
    apiEndpoints:
      - credits
    policies:
      - cors:
          - action:
              origin: "*"
      - proxy:
          - action:
              serviceEndpoint: creditsService
              changeOrigin: true
  payments:
    apiEndpoints:
      - payments
    policies:
      - cors:
          - action:
              origin: "*"
      - proxy:
          - action:
              serviceEndpoint: paymentsService 
              changeOrigin: true
  transactions:
    apiEndpoints:
      - transactions
    policies:
      - cors:
          - action:
              origin: "*"
      - proxy:
          - action:
              serviceEndpoint: transactionsService
              changeOrigin: true